# see https://github.com/cmaessen/docker-php-sendmail for more information


FROM php:7-fpm-alpine
RUN docker-php-ext-install mysqli
# RUN apk add php7-gd php7-mysqli php7-zlib php7-curl

# # Update system core
# RUN apt update -y && apt upgrade -y
# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# # Start PHP-FPM
# CMD ["php-fpm"]

# --------------
# FROM php:7-fpm

# RUN apt-get update 
# RUN apt-get install -q -y ssmtp mailutils && rm -rf /var/lib/apt/lists/*

# RUN docker-php-ext-install mysql mysqli sysvsem

# RUN pecl install xdebug-2.5.5 \
#     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
#     && echo "[XDebug]" >> /usr/local/etc/php/conf.d/xdebug.ini \
#     && echo "xdebug.remote_log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini \
#     && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
#     && echo "xdebug.remote_autostart=on" >> /usr/local/etc/php/conf.d/xdebug.ini

# RUN echo "hostname=localhost.localdomain" > /etc/ssmtp/ssmtp.conf \
#     && echo "root=root@localhost" >> /etc/ssmtp/ssmtp.conf \
#     && echo "mailhub=maildev" >> /etc/ssmtp/ssmtp.conf \
#     && echo "sendmail_path=sendmail -i -t" >> /usr/local/etc/php/conf.d/php-sendmail.ini

# RUN echo "[Date]" >> /usr/local/etc/php/conf.d/php-sendmail.ini \
#     && echo "date.timezone = Europe/Amsterdam" >> /usr/local/etc/php/conf.d/php-sendmail.ini

# RUN echo "localhost localhost.localdomain" >> /etc/hosts