web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  # image: php:7-fpm
  container_name: docker-compose_php_1
  build: .
  volumes: 
    - ./code:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
#    - maildev

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

# maildev:
#   image: djfarrelly/maildev
#   ports:
#    - "9081:80"
