#
# docker-compose for stage and prod
#
version: "3"

services:
    nginx:
      # take an image that supports php
      image: richarvey/nginx-php-fpm:latest
      container_name: angular-errorhandler 
      restart: always
      volumes:
        # mount working_dir for docker-compose
        - ./:/code
        # mount configuration for nginx 
        # - ./default.conf:/etc/nginx/conf.d/default.conf
        # - ./default.conf:/etc/nginx/sites-available/default.conf
        # mount dist/cometa-rocks-website to html-root of nginx
        # - ./dist/cometa-rocks-website:/var/www/html
        # mount php direcotry to be available to nginx inside document root
      working_dir: /code
      environment:
        - PHP_ERRORS_STDERR=TRUE
      ports:
        - "4200:4200"
      # 
      # prepare.sh Command installs npm, compiles and copies result to html folder of nginx
      #
      command: bash -c "/start.sh"
